version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - sudo apt-get install gcc libpq-dev -y
      - sudo apt-get install python-dev  python-pip -y
      - sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
      - pip3 install wheel
      - pip install twine
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python setup.py sdist bdist_wheel
      - twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u $(username) -p $(password)
