version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install --upgrade setuptools wheel
      - pip install twine
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python setup.py sdist bdist_wheel
      - twine upload -u sinoj -p Debited@12 -repository-url https://test.pypi.org/legacy/ dist / * 

artifacts:
  files: 
    - '**/*'
