version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip install wheel
      - pip install twine
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - python setup.py sdist bdist_wheel
      - twine upload --repository-url https://test.pypi.org/ dist/* --username sinoj --password Debited@12
